#!/usr/bin/env sh
# Generate the jud plugin's format reference from the specification, so the
# plugin ships the one normative text and cannot drift from it.
#
#   scripts/gen-plugin-format.sh            write plugins/jud/skills/jud/references/format.md
#   scripts/gen-plugin-format.sh --check    exit 1 when the committed file is stale
#
# The source is docs/reference/jud-format.md. Its frontmatter is dropped, a
# header says where the text came from, and every relative link is rewritten
# to an absolute URL on the repository's default branch, because the plugin
# is read on its own, outside this checkout. POSIX sh and sed only.
set -eu

root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
cd "$root"
src=docs/reference/jud-format.md
out=plugins/jud/skills/jud/references/format.md
base=https://github.com/chussenot/judgment/blob/main

mode=write
if [ "${1:-}" = "--check" ]; then
  mode=check
fi

tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT

{
  printf '<!-- Generated by scripts/gen-plugin-format.sh from %s. Do not edit; edit the specification and run the script. -->\n\n' "$src"
  # The body without its frontmatter block.
  awk 'NR == 1 && $0 == "---" { infm = 1; next } infm && $0 == "---" { infm = 0; next } !infm' "$src" \
    | sed -E \
        -e "s#\]\(\.\./\.\./([^)#]+)#](${base}/\1#g" \
        -e "s#\]\(\.\./([^)#]+)#](${base}/docs/\1#g" \
        -e "s#\]\(([A-Za-z0-9_-]+\.md)#](${base}/docs/reference/\1#g"
} > "$tmp"

case "$mode" in
  write)
    if cmp -s "$tmp" "$out"; then
      echo "$out is up to date"
    else
      cp "$tmp" "$out"
      echo "wrote $out"
    fi
    ;;
  check)
    if cmp -s "$tmp" "$out"; then
      echo "$out matches $src"
    else
      diff -u "$out" "$tmp" >&2 || true
      echo "$out is stale: run scripts/gen-plugin-format.sh and commit the result" >&2
      exit 1
    fi
    ;;
esac
