//! `support-routing` as Rust: its answers as typed values, its questions
//! and policy from `examples/jud/routing.jud`.
//!
//! Generated by the jud plugin's `/jud:rust` from `examples/jud/routing.jud`,
//! questions `sha256:3d6813675de1d05e1f7b93bc325cf52f22ad82411cc2036cd8f6a57e7a64f6e6`.
//! The file is compiled in (`include_str!`) and parsed at run time:
//!
//! - a change to the policy (a bar, a band, a fallback, `jud tune`) takes a
//!   rebuild, which cargo does on its own, and no regeneration;
//! - a change to a question takes a regeneration, and the test at the bottom
//!   fails until it is done.
//!
//! Two questions take options the program supplies with each request
//! ([`Offered`]): `desk` always, with at least one desk, and `duplicate_of`
//! whenever the state has `customer.open_tickets`, with at least one
//! ticket. A supplied key must not be the question's own (`none_of_these`,
//! `none`). Two questions are asked only when the state carries what they
//! are about, so their fields are `Option`s: a path counts when it is
//! present and not null, `""`, `[]` or `{}`.
//!
//! ```ignore
//! mod routing;
//! use routing::{Desk, Gated, Offered};
//!
//! #[tokio::main(flavor = "current_thread")]
//! async fn main() -> Result<(), Box<dyn std::error::Error>> {
//!     let backend = judgment::Client::from_env()?; // or judgment::Fake, judgment::Replay
//!     let state = serde_json::json!({ "message": { "text": "Refund my order, please." } });
//!     let offered = Offered {
//!         desk: vec![
//!             ("billing".into(), "Invoices, payments, refunds".into()),
//!             ("technical".into(), "Errors and how-to questions".into()),
//!         ],
//!         ..Offered::default() // no open tickets in this state
//!     };
//!     let decision = routing::decide(&backend, "jev-latest", &state, &offered).await?;
//!     match &decision.desk {
//!         Gated::Act { value: Desk::Supplied(desk), band, .. } => {
//!             println!("to {desk}, band {band:?}"); // the policy's bands: route or confirm
//!         }
//!         Gated::Act { value: Desk::NoneOfThese, .. } | Gated::Defer { .. } => {
//!             println!("a person sorts it");
//!         }
//!     }
//!     // `reached` carries the policy's `level_at_least`, so no level is named here.
//!     if matches!(decision.tone, Gated::Act { reached: Some(true), .. }) {
//!         println!("a team lead reads it first");
//!     }
//!     if let Some(refund) = decision.refund_request {
//!         println!("refund asked: {}", refund.yes); // asked: the state had customer.recent_orders
//!     }
//!     Ok(())
//! }
//! ```

// A generated API: a program uses the parts it needs and no warning should
// ask it to delete the rest.
#![allow(dead_code)]

use std::sync::OnceLock;

use judgment::jud::{Rubric, Supplied, Verdict};
use judgment::{Questions, Response, SystemOne};

/// The rubric's text, compiled in from the file and parsed at run time.
/// The request is lowered from it, so it is byte for byte what `jud lower`
/// sends for the same file, and recordings made with `jud record` replay
/// against it.
pub const SOURCE: &str = include_str!("routing.jud");

/// The rubric's path from the crate root, as errors and the test name it.
pub const RUBRIC: &str = "examples/jud/routing.jud";

/// The questions fingerprint this module was generated from (`jud check`).
pub const QUESTIONS_FINGERPRINT: &str =
    "sha256:3d6813675de1d05e1f7b93bc325cf52f22ad82411cc2036cd8f6a57e7a64f6e6";

/// The parsed rubric, read once.
///
/// # Errors
///
/// [`Error::Rubric`] when [`SOURCE`] is not a valid rubric, which the test
/// below rules out.
pub fn rubric() -> Result<&'static Rubric, Error> {
    static PARSED: OnceLock<Rubric> = OnceLock::new();
    if let Some(rubric) = PARSED.get() {
        return Ok(rubric);
    }
    let parsed = Rubric::parse(SOURCE)?;
    Ok(PARSED.get_or_init(|| parsed))
}

/// Which desk should take `message`? The desks staffed now are supplied
/// with each request ([`Offered::desk`]), before the static option.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum Desk {
    /// `none_of_these`: Not clearly any desk staffed now
    NoneOfThese,
    /// A desk the program supplied, by its key.
    Supplied(String),
}

impl Desk {
    /// The option's key on the wire.
    #[must_use]
    pub fn key(&self) -> &str {
        match self {
            Self::NoneOfThese => "none_of_these",
            Self::Supplied(key) => key,
        }
    }

    /// Any key the response names is one the request offered
    /// (`Response::verify`), so every key reads.
    fn from_key(key: &str) -> Self {
        match key {
            "none_of_these" => Self::NoneOfThese,
            other => Self::Supplied(other.to_owned()),
        }
    }
}

/// How upset is the writer of `message`? Lowest level first, so `>=`
/// compares levels.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum Tone {
    /// `calm` (level 0)
    Calm,
    /// `annoyed` (level 1)
    Annoyed,
    /// `angry` (level 2)
    Angry,
    /// `abusive` (level 3)
    Abusive,
}

impl Tone {
    /// Every level, lowest first.
    pub const ALL: [Self; 4] = [Self::Calm, Self::Annoyed, Self::Angry, Self::Abusive];

    /// The level's text in the rubric.
    #[must_use]
    pub const fn label(self) -> &'static str {
        match self {
            Self::Calm => "calm",
            Self::Annoyed => "annoyed",
            Self::Angry => "angry",
            Self::Abusive => "abusive",
        }
    }

    /// A level by its index, as a verdict names it, or by its text, as a
    /// policy's `fallback` may: the index first, as the rubric reads it.
    fn from_level(level: &str) -> Result<Self, Error> {
        level
            .parse::<usize>()
            .ok()
            .and_then(|i| Self::ALL.get(i).copied())
            .or_else(|| Self::ALL.into_iter().find(|l| l.label() == level))
            .ok_or_else(|| Error::unexpected("tone", level))
    }
}

/// Which entry in `customer.open_tickets` is `message` about? The open
/// tickets are supplied with each request ([`Offered::duplicate_of`]).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum DuplicateOf {
    /// `none`: A new request, not about an open ticket. Named so that it
    /// is not read as `Option::None`, which means the question was not asked.
    NoneOption,
    /// A ticket the program supplied, by its key.
    Supplied(String),
}

impl DuplicateOf {
    /// The option's key on the wire.
    #[must_use]
    pub fn key(&self) -> &str {
        match self {
            Self::NoneOption => "none",
            Self::Supplied(key) => key,
        }
    }

    /// Any key the response names is one the request offered
    /// (`Response::verify`), so every key reads.
    fn from_key(key: &str) -> Self {
        match key {
            "none" => Self::NoneOption,
            other => Self::Supplied(other.to_owned()),
        }
    }
}

/// The options the program supplies with a request, key and description,
/// in the order the model should see them.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Offered {
    /// The desks staffed now, for `desk`: at least one, since the rubric
    /// offers one option of its own and a Choice needs two, and none keyed
    /// `none_of_these`.
    pub desk: Vec<(String, String)>,
    /// The customer's open tickets, for `duplicate_of`: at least one
    /// whenever the state has `customer.open_tickets`, when the question is
    /// asked, and none keyed `none`, which is refused even when it is not.
    pub duplicate_of: Vec<(String, String)>,
}

impl Offered {
    fn supplied(&self) -> Supplied {
        let mut supplied = Supplied::default();
        for (id, options) in [("desk", &self.desk), ("duplicate_of", &self.duplicate_of)] {
            if !options.is_empty() {
                supplied.insert(
                    id.to_owned(),
                    options
                        .iter()
                        .map(|(key, text)| (key.clone(), serde_json::Value::from(text.as_str())))
                        .collect(),
                );
            }
        }
        supplied
    }
}

/// A Noul's verdict: the gate's yes or no, and the probability of yes it
/// was read from.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct YesNo {
    /// The gate's answer: the probability met its threshold (exceeded it,
    /// when the gate is `strict`).
    pub yes: bool,
    /// The model's probability of yes.
    pub probability: f64,
}

/// A Choice's or a Score's verdict.
#[derive(Debug, Clone, PartialEq)]
pub enum Gated<T> {
    /// The answer met the gate's bar, or the question has no gate: act on
    /// `value`.
    Act {
        /// The option or level.
        value: T,
        /// The answer's confidence.
        confidence: f64,
        /// The band it reached, when the gate has `bands`.
        band: Option<String>,
        /// For a Score whose gate has `level_at_least`: whether it reached it.
        reached: Option<bool>,
    },
    /// The answer was below the gate's last bar: do not act on it alone.
    Defer {
        /// What the model would have answered.
        nearest: T,
        /// The gate's fallback, when it has one.
        fallback: Option<T>,
        /// The answer's confidence.
        confidence: f64,
        /// The bar it was below.
        bar: f64,
    },
}

impl<T: Clone> Gated<T> {
    /// What to act on: the answer when it met the bar, else the fallback.
    #[must_use]
    pub fn or_fallback(&self) -> Option<T> {
        match self {
            Self::Act { value, .. } => Some(value.clone()),
            Self::Defer { fallback, .. } => fallback.clone(),
        }
    }
}

/// Every question's verdict, typed. The bars that decide them are the
/// rubric's policy, read from the file.
#[derive(Debug, Clone, PartialEq)]
pub struct Decision {
    /// Which desk should take `message`? `band` names the policy's band
    /// the answer reached, when the policy has bands.
    pub desk: Gated<Desk>,
    /// How upset is the writer of `message`? `reached` says whether it met
    /// the policy's `level_at_least`, when it has one.
    pub tone: Gated<Tone>,
    /// Which entry in `customer.open_tickets` is `message` about? `None`
    /// when the state's `customer.open_tickets` is absent, null or empty.
    pub duplicate_of: Option<Gated<DuplicateOf>>,
    /// Does `message` ask for a refund for one of `customer.recent_orders`?
    /// `None` when the state's `customer.recent_orders` is absent, null or
    /// empty.
    pub refund_request: Option<YesNo>,
}

/// The request for `state`, as the rubric lowers it.
///
/// # Errors
///
/// [`Error::Rubric`] when the state cannot be lowered: a supplied option
/// that clashes with a static one, or too few options in all.
pub fn questions(state: &serde_json::Value, offered: &Offered) -> Result<Questions, Error> {
    Ok(rubric()?.lower(state, &offered.supplied())?)
}

/// Read `response`, the answer to `asked`, through the rubric's policy.
///
/// # Errors
///
/// [`Error::Rubric`] when the response does not answer `asked`;
/// [`Error::Missing`] when the rubric no longer asks a question this module
/// reads, and [`Error::Unexpected`] when an answer names something this
/// module does not know: both mean it is older than the rubric.
pub fn read(asked: &Questions, response: &Response) -> Result<Decision, Error> {
    let verdicts = rubric()?.apply(asked, response)?;
    let verdict = |id: &'static str| verdicts.get(id).ok_or(Error::Missing(id));
    Ok(Decision {
        desk: gated("desk", verdict("desk")?, |key| Ok(Desk::from_key(key)))?,
        tone: gated("tone", verdict("tone")?, Tone::from_level)?,
        duplicate_of: verdicts
            .get("duplicate_of")
            .map(|v| gated("duplicate_of", v, |key| Ok(DuplicateOf::from_key(key))))
            .transpose()?,
        refund_request: verdicts
            .get("refund_request")
            .map(|v| yes_no("refund_request", v))
            .transpose()?,
    })
}

/// Ask `backend` about `state` with `model`, offering `offered`, and read
/// the answer.
///
/// # Errors
///
/// [`Error::State`] when `state` does not serialise to JSON,
/// [`Error::Backend`] when the call fails, and what [`read`] returns.
pub async fn decide<B: SystemOne>(
    backend: &B,
    model: &str,
    state: &impl serde::Serialize,
    offered: &Offered,
) -> Result<Decision, Error> {
    let state = serde_json::to_value(state).map_err(Error::State)?;
    let asked = questions(&state, offered)?;
    let response = backend.answer(&state, model, &asked).await?;
    read(&asked, &response)
}

fn yes_no(id: &'static str, verdict: &Verdict) -> Result<YesNo, Error> {
    match verdict {
        Verdict::Yes { probability } => Ok(YesNo {
            yes: true,
            probability: probability.value(),
        }),
        Verdict::No { probability } => Ok(YesNo {
            yes: false,
            probability: probability.value(),
        }),
        other => Err(Error::unexpected(id, &format!("{other:?}"))),
    }
}

/// A Choice's verdict names an option key, a Score's a level index (its
/// fallback may name the level's text); `parse` turns either into this
/// module's type.
fn gated<T>(
    id: &'static str,
    verdict: &Verdict,
    parse: impl Fn(&str) -> Result<T, Error>,
) -> Result<Gated<T>, Error> {
    match verdict {
        Verdict::Option {
            key,
            confidence,
            band,
            ..
        } => Ok(Gated::Act {
            value: parse(key)?,
            confidence: confidence.value(),
            band: band.clone(),
            reached: None,
        }),
        Verdict::Level {
            index,
            confidence,
            band,
            reached,
            ..
        } => Ok(Gated::Act {
            value: parse(&index.to_string())?,
            confidence: confidence.value(),
            band: band.clone(),
            reached: *reached,
        }),
        Verdict::Deferred(deferred) => Ok(Gated::Defer {
            nearest: parse(&deferred.nearest)?,
            fallback: deferred.fallback.as_deref().map(&parse).transpose()?,
            confidence: deferred.confidence.value(),
            bar: deferred.bar,
        }),
        other => Err(Error::unexpected(id, &format!("{other:?}"))),
    }
}

/// What can go wrong between the rubric, the backend and this module.
#[derive(Debug)]
pub enum Error {
    /// The rubric did not parse, lower or read the response.
    Rubric(judgment::jud::Error),
    /// The state did not serialise to JSON.
    State(serde_json::Error),
    /// The backend call failed.
    Backend(judgment::Error),
    /// A question this module reads has no verdict: the rubric no longer
    /// asks it, so this module is older than the rubric.
    Missing(&'static str),
    /// A verdict this module cannot type: it is older than the rubric.
    Unexpected {
        /// The question.
        question: &'static str,
        /// What the verdict held.
        found: String,
    },
}

impl Error {
    fn unexpected(question: &'static str, found: &str) -> Self {
        Self::Unexpected {
            question,
            found: found.to_owned(),
        }
    }
}

impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Rubric(e) => write!(f, "{RUBRIC}: {e}"),
            Self::State(e) => write!(f, "state: {e}"),
            Self::Backend(e) => write!(f, "backend: {e}"),
            Self::Missing(id) => write!(
                f,
                "no verdict for `{id}`; regenerate this module from {RUBRIC}"
            ),
            Self::Unexpected { question, found } => write!(
                f,
                "`{question}`: unexpected {found}; regenerate this module from {RUBRIC}"
            ),
        }
    }
}

impl std::error::Error for Error {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::Rubric(e) => Some(e),
            Self::State(e) => Some(e),
            Self::Backend(e) => Some(e),
            Self::Missing(_) | Self::Unexpected { .. } => None,
        }
    }
}

impl From<judgment::jud::Error> for Error {
    fn from(e: judgment::jud::Error) -> Self {
        Self::Rubric(e)
    }
}

impl From<judgment::Error> for Error {
    fn from(e: judgment::Error) -> Self {
        Self::Backend(e)
    }
}

#[cfg(test)]
mod tests {
    use judgment::Question;

    use super::*;

    /// Fails when the rubric's questions changed since this module was
    /// generated: regenerate it.
    #[test]
    fn the_module_matches_the_rubric() -> Result<(), Error> {
        let rubric = rubric()?;
        assert_eq!(
            rubric.fingerprint(),
            QUESTIONS_FINGERPRINT,
            "{RUBRIC}'s questions changed: regenerate this module"
        );
        let static_keys = |id: &str| match rubric.questions.get(id).map(|q| &q.question) {
            Some(Question::Choice { criteria, .. }) => {
                criteria.keys().map(String::as_str).collect::<Vec<_>>()
            }
            _ => Vec::new(),
        };
        assert_eq!(static_keys("desk"), [Desk::NoneOfThese.key()]);
        assert_eq!(static_keys("duplicate_of"), [DuplicateOf::NoneOption.key()]);
        let tone = rubric.questions.get("tone").map(|q| &q.question);
        assert!(
            matches!(tone, Some(Question::Score { criteria, .. })
                if criteria.iter().map(|l| l.as_str()).eq(Tone::ALL.map(|t| Some(t.label())))),
            "tone's levels are not {:?}",
            Tone::ALL.map(Tone::label)
        );
        Ok(())
    }

    /// A Score's fallback may name a level by its text, a verdict by its
    /// index: both read.
    #[test]
    fn levels_read_by_index_and_by_text() -> Result<(), Error> {
        for (index, level) in Tone::ALL.into_iter().enumerate() {
            assert_eq!(Tone::from_level(&index.to_string())?, level);
            assert_eq!(Tone::from_level(level.label())?, level);
        }
        Ok(())
    }
}
