//! `inbox-triage` (triage.jud) as Rust: the rubric's questions and policy
//! read from the `.jud` file at compile time, its answers as typed values.
//!
//! Generated by the jud plugin's `/jud:rust` from `triage.jud`, questions
//! `sha256:fda347c2cba6deaa8ad784360c46a8289adbc0284b373c3d9162ce11f3e7ac8a`.
//! Regenerate it when a question changes; the test at the bottom fails until
//! you do. A change to the policy (a bar, a fallback, `jud tune`) needs no
//! regeneration: the bars are read from the file.
//!
//! ```ignore
//! let decision = triage::decide(&backend, "jev-latest", &state).await?;
//! if decision.actionable.yes {
//!     match decision.desk {
//!         triage::Gated::Act { value: triage::Desk::Billing, .. } => { /* ... */ }
//!         triage::Gated::Act { .. } | triage::Gated::Defer { .. } => { /* ... */ }
//!     }
//! }
//! ```

// A generated API: a program uses the parts it needs and no warning should
// ask it to delete the rest.
#![allow(dead_code)]

use std::sync::OnceLock;

use judgment::jud::{Rubric, Supplied, Verdict};
use judgment::{Questions, Response, SystemOne};

/// The rubric, as written. The request is lowered from it, so it is
/// byte for byte what `jud lower` sends, and recordings made with `jud
/// record` replay against it.
pub const SOURCE: &str = include_str!("triage.jud");

/// The questions fingerprint this module was generated from (`jud check`).
pub const QUESTIONS_FINGERPRINT: &str =
    "sha256:fda347c2cba6deaa8ad784360c46a8289adbc0284b373c3d9162ce11f3e7ac8a";

/// The parsed rubric, read once.
///
/// # Errors
///
/// [`Error::Rubric`] when [`SOURCE`] is not a valid rubric, which the test
/// below rules out.
pub fn rubric() -> Result<&'static Rubric, Error> {
    static RUBRIC: OnceLock<Rubric> = OnceLock::new();
    if let Some(rubric) = RUBRIC.get() {
        return Ok(rubric);
    }
    let parsed = Rubric::parse(SOURCE)?;
    Ok(RUBRIC.get_or_init(|| parsed))
}

/// Which desk should take `message`?
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Desk {
    /// Invoices, payments, refunds, subscription changes
    Billing,
    /// Errors, outages, anything about using the product
    Technical,
    /// Sign-in, passwords, personal details, closing an account
    Account,
    /// Not clearly any desk, or not a request at all
    NoneOfThese,
}

impl Desk {
    /// Every option, in the order the model sees them.
    pub const ALL: [Self; 4] = [
        Self::Billing,
        Self::Technical,
        Self::Account,
        Self::NoneOfThese,
    ];

    /// The option's key on the wire and in the rubric.
    #[must_use]
    pub const fn key(self) -> &'static str {
        match self {
            Self::Billing => "billing",
            Self::Technical => "technical",
            Self::Account => "account",
            Self::NoneOfThese => "none_of_these",
        }
    }

    fn from_key(key: &str) -> Result<Self, Error> {
        Self::ALL
            .into_iter()
            .find(|option| option.key() == key)
            .ok_or_else(|| Error::unexpected("desk", key))
    }
}

/// How upset is the writer of `message`? Lowest level first, so `>=`
/// compares levels.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum Tone {
    /// calm
    Calm,
    /// annoyed
    Annoyed,
    /// angry
    Angry,
}

impl Tone {
    /// Every level, lowest first.
    pub const ALL: [Self; 3] = [Self::Calm, Self::Annoyed, Self::Angry];

    /// The level's text in the rubric.
    #[must_use]
    pub const fn label(self) -> &'static str {
        match self {
            Self::Calm => "calm",
            Self::Annoyed => "annoyed",
            Self::Angry => "angry",
        }
    }

    fn from_index(index: &str) -> Result<Self, Error> {
        index
            .parse::<usize>()
            .ok()
            .and_then(|i| Self::ALL.get(i).copied())
            .ok_or_else(|| Error::unexpected("tone", index))
    }
}

/// A Noul's verdict: the gate's yes or no, and the probability of yes it
/// was read from.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct YesNo {
    /// Whether the probability met the gate's threshold.
    pub yes: bool,
    /// The model's probability of yes.
    pub probability: f64,
}

/// A Choice's or a Score's verdict.
#[derive(Debug, Clone, PartialEq)]
pub enum Gated<T> {
    /// The answer met the gate's bar: act on `value`.
    Act {
        /// The option or level.
        value: T,
        /// The answer's confidence.
        confidence: f64,
        /// The band it reached, when the gate has `bands`.
        band: Option<String>,
        /// For a Score whose gate has `level_at_least`: whether it reached it.
        reached: Option<bool>,
    },
    /// The answer was below the gate's last bar: do not act on it alone.
    Defer {
        /// What the model would have answered.
        nearest: T,
        /// The gate's fallback, when it has one.
        fallback: Option<T>,
        /// The answer's confidence.
        confidence: f64,
        /// The bar it was below.
        bar: f64,
    },
}

impl<T: Copy> Gated<T> {
    /// What to act on: the answer when it met the bar, else the fallback.
    #[must_use]
    pub fn or_fallback(&self) -> Option<T> {
        match self {
            Self::Act { value, .. } => Some(*value),
            Self::Defer { fallback, .. } => *fallback,
        }
    }
}

/// Every question's verdict, typed.
#[derive(Debug, Clone, PartialEq)]
pub struct Decision {
    /// Does `message` ask for something to be done, or report something
    /// that is broken?
    pub actionable: YesNo,
    /// Which desk should take `message`?
    pub desk: Gated<Desk>,
    /// How upset is the writer of `message`?
    pub tone: Gated<Tone>,
}

/// The request for `state`, as the rubric lowers it.
///
/// # Errors
///
/// [`Error::Rubric`] when the state cannot be lowered.
pub fn questions(state: &serde_json::Value) -> Result<Questions, Error> {
    Ok(rubric()?.lower(state, &Supplied::default())?)
}

/// Read `response`, the answer to `asked`, through the rubric's policy.
///
/// # Errors
///
/// [`Error::Rubric`] when the response does not answer `asked`;
/// [`Error::Unexpected`] when an answer names something this module does not
/// know, which means it is older than the rubric.
pub fn read(asked: &Questions, response: &Response) -> Result<Decision, Error> {
    let verdicts = rubric()?.apply(asked, response)?;
    let verdict = |id: &'static str| verdicts.get(id).ok_or(Error::Missing(id));
    Ok(Decision {
        actionable: yes_no("actionable", verdict("actionable")?)?,
        desk: gated("desk", verdict("desk")?, Desk::from_key)?,
        tone: gated("tone", verdict("tone")?, Tone::from_index)?,
    })
}

/// Ask `backend` about `state` with `model` and read the answer.
///
/// # Errors
///
/// [`Error::Backend`] when the call fails, and what [`read`] returns.
pub async fn decide<B: SystemOne>(
    backend: &B,
    model: &str,
    state: &impl serde::Serialize,
) -> Result<Decision, Error> {
    let state = serde_json::to_value(state).map_err(|e| Error::Backend(e.into()))?;
    let asked = questions(&state)?;
    let response = backend.answer(&state, model, &asked).await?;
    read(&asked, &response)
}

fn yes_no(id: &'static str, verdict: &Verdict) -> Result<YesNo, Error> {
    match verdict {
        Verdict::Yes { probability } => Ok(YesNo {
            yes: true,
            probability: probability.value(),
        }),
        Verdict::No { probability } => Ok(YesNo {
            yes: false,
            probability: probability.value(),
        }),
        other => Err(Error::unexpected(id, &format!("{other:?}"))),
    }
}

/// A Choice's verdict names an option key, a Score's a level index; `parse`
/// turns either into this module's type.
fn gated<T>(
    id: &'static str,
    verdict: &Verdict,
    parse: impl Fn(&str) -> Result<T, Error>,
) -> Result<Gated<T>, Error> {
    match verdict {
        Verdict::Option {
            key,
            confidence,
            band,
            ..
        } => Ok(Gated::Act {
            value: parse(key)?,
            confidence: confidence.value(),
            band: band.clone(),
            reached: None,
        }),
        Verdict::Level {
            index,
            confidence,
            band,
            reached,
            ..
        } => Ok(Gated::Act {
            value: parse(&index.to_string())?,
            confidence: confidence.value(),
            band: band.clone(),
            reached: *reached,
        }),
        Verdict::Deferred(deferred) => Ok(Gated::Defer {
            nearest: parse(&deferred.nearest)?,
            fallback: deferred.fallback.as_deref().map(&parse).transpose()?,
            confidence: deferred.confidence.value(),
            bar: deferred.bar,
        }),
        other => Err(Error::unexpected(id, &format!("{other:?}"))),
    }
}

/// What can go wrong between the rubric, the backend and this module.
#[derive(Debug)]
#[non_exhaustive]
pub enum Error {
    /// The rubric did not parse, lower or read the response.
    Rubric(judgment::jud::Error),
    /// The backend call failed.
    Backend(judgment::Error),
    /// The rubric asked a question the response has no verdict for.
    Missing(&'static str),
    /// A verdict this module cannot type: it is older than the rubric.
    Unexpected {
        /// The question.
        question: &'static str,
        /// What the verdict held.
        found: String,
    },
}

impl Error {
    fn unexpected(question: &'static str, found: &str) -> Self {
        Self::Unexpected {
            question,
            found: found.to_owned(),
        }
    }
}

impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Rubric(e) => write!(f, "triage.jud: {e}"),
            Self::Backend(e) => write!(f, "backend: {e}"),
            Self::Missing(id) => write!(f, "no verdict for `{id}`"),
            Self::Unexpected { question, found } => write!(
                f,
                "`{question}`: unexpected {found}; regenerate this module from triage.jud"
            ),
        }
    }
}

impl std::error::Error for Error {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::Rubric(e) => Some(e),
            Self::Backend(e) => Some(e),
            Self::Missing(_) | Self::Unexpected { .. } => None,
        }
    }
}

impl From<judgment::jud::Error> for Error {
    fn from(e: judgment::jud::Error) -> Self {
        Self::Rubric(e)
    }
}

impl From<judgment::Error> for Error {
    fn from(e: judgment::Error) -> Self {
        Self::Backend(e)
    }
}

#[cfg(test)]
mod tests {
    use judgment::Question;

    use super::*;

    /// Fails when triage.jud's questions changed since this module was
    /// generated: regenerate it.
    #[test]
    fn the_module_matches_the_rubric() -> Result<(), Error> {
        let rubric = rubric()?;
        assert_eq!(
            rubric.fingerprint(),
            QUESTIONS_FINGERPRINT,
            "triage.jud's questions changed: regenerate this module"
        );
        let desk = rubric.questions.get("desk").map(|q| &q.question);
        assert!(
            matches!(desk, Some(Question::Choice { criteria, .. })
                if criteria.keys().map(String::as_str).eq(Desk::ALL.map(Desk::key))),
            "desk's options are not {:?}",
            Desk::ALL.map(Desk::key)
        );
        let tone = rubric.questions.get("tone").map(|q| &q.question);
        assert!(
            matches!(tone, Some(Question::Score { criteria, .. })
                if criteria.iter().map(|l| l.as_str()).eq(Tone::ALL.map(|t| Some(t.label())))),
            "tone's levels are not {:?}",
            Tone::ALL.map(Tone::label)
        );
        Ok(())
    }
}
